version: '3'
services:
    directus:
        image: directus/directus:10.13.0
        env_file: '.env.local'
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
